# Generated by Django 6.0.1 on 2026-01-26 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_alter_trade_result'),
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='side',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='trade',
            name='symbol',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='trade',
            name='strategy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='strategies.strategy'),
        ),
    ]
