# Generated by Django 6.0.1 on 2026-01-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_trade_external_id_trade_side_trade_symbol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='image_after',
            field=models.ImageField(blank=True, null=True, upload_to='trades/after/'),
        ),
        migrations.AddField(
            model_name='trade',
            name='image_before',
            field=models.ImageField(blank=True, null=True, upload_to='trades/before/'),
        ),
        migrations.AddField(
            model_name='trade',
            name='image_live',
            field=models.ImageField(blank=True, null=True, upload_to='trades/live/'),
        ),
    ]
