# Generated by Django 5.2.7 on 2026-02-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_trade_image_after_trade_image_before_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID from Binance/MT5', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='followed_plan',
            field=models.BooleanField(default=True, help_text='Automatically set based on checklist completion'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='image_after',
            field=models.ImageField(blank=True, help_text='Exit outcome', null=True, upload_to='trades/after/'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='image_before',
            field=models.ImageField(blank=True, help_text='Entry setup', null=True, upload_to='trades/before/'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='image_live',
            field=models.ImageField(blank=True, help_text='Intra-trade status', null=True, upload_to='trades/live/'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='notes',
            field=models.TextField(blank=True, help_text="User's reflection on the trade"),
        ),
        migrations.AlterField(
            model_name='trade',
            name='pnl',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Profit or Loss value', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='side',
            field=models.CharField(blank=True, help_text='BUY or SELL', max_length=10),
        ),
        migrations.AlterField(
            model_name='trade',
            name='symbol',
            field=models.CharField(blank=True, help_text='e.g., BTCUSDT, EURUSD', max_length=50),
        ),
    ]
