from django.db import models
from django.conf import settings

class Strategy(models.Model):
    """
    Represents a user-defined trading strategy.
    Strategies are the core of Guard AI, combining AI-generated checklist items
    with user-uploaded chart screenshots for visual confirmation.
    """
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='strategies')
    name = models.CharField(max_length=255, help_text="User-friendly name for the strategy")
    description = models.TextField(help_text="Natural language description used by Gemini to generate the checklist")
    is_public = models.BooleanField(default=False, help_text="Allow other traders to view this strategy")
    created_at = models.DateTimeField(auto_now_add=True)
    
    # JSON field storing the AI-generated verification rules
    checklist_items = models.JSONField(default=list, help_text="List of rules to check before entry, generated by AI")
    
    # Visual references: Screenshots showing what a valid setup looks like on a real chart
    chart_image_1 = models.ImageField(upload_to='strategies/charts/', null=True, blank=True)
    chart_image_2 = models.ImageField(upload_to='strategies/charts/', null=True, blank=True)
    chart_image_3 = models.ImageField(upload_to='strategies/charts/', null=True, blank=True)
    
    def __str__(self):
        return f"{self.name} ({self.user.email})"


class CustomRule(models.Model):
    """
    Allows users to add specific visual 'protocols' or manual rules to a strategy.
    Each custom rule can include its own explanatory image (e.g., a specific candle pattern).
    """
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='custom_rules')
    strategy = models.ForeignKey(Strategy, on_delete=models.CASCADE, related_name='custom_rules', null=True, blank=True)
    title = models.CharField(max_length=100)
    description = models.TextField()
    image_example = models.ImageField(upload_to='rules/examples/', null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.title} - {self.user.email}"

