# Generated by Django 5.2.7 on 2026-02-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0002_customrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='chart_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='strategies/charts/'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='chart_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='strategies/charts/'),
        ),
        migrations.AddField(
            model_name='strategy',
            name='chart_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='strategies/charts/'),
        ),
        migrations.AlterField(
            model_name='customrule',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
