# Generated by Django 5.2.7 on 2026-02-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0003_strategy_chart_image_1_strategy_chart_image_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Allow other traders to view this strategy'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='checklist_items',
            field=models.JSONField(default=list, help_text='List of rules to check before entry, generated by AI'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='description',
            field=models.TextField(help_text='Natural language description used by Gemini to generate the checklist'),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='name',
            field=models.CharField(help_text='User-friendly name for the strategy', max_length=255),
        ),
    ]
