# Generated by Django 6.0.1 on 2026-01-26 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_type', models.CharField(choices=[('BINANCE', 'Binance'), ('BYBIT', 'Bybit'), ('KRAKEN', 'Kraken'), ('COINBASE', 'Coinbase'), ('METATRADER', 'MetaTrader 5'), ('OTHER', 'Other Exchange')], max_length=20)),
                ('nickname', models.CharField(blank=True, help_text="e.g., 'My Binance Spot'", max_length=100)),
                ('_api_key', models.TextField(db_column='api_key')),
                ('_api_secret', models.TextField(db_column='api_secret')),
                ('mt_server', models.CharField(blank=True, help_text="e.g., 'ICMarkets-Demo'", max_length=100)),
                ('mt_login', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'broker_type', 'nickname')},
            },
        ),
    ]
