# Generated by Django 6.0.1 on 2026-02-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_brokerconnection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokerconnection',
            name='nickname',
            field=models.CharField(blank=True, help_text="User's personal label for this account", max_length=100),
        ),
    ]
