# Generated by Django 5.2.7 on 2026-05-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_bio_alter_brokerconnection_id_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokerconnection',
            name='mt_account_id',
            field=models.CharField(blank=True, help_text='MetaApi internal account ID', max_length=100),
        ),
        migrations.AddField(
            model_name='brokerconnection',
            name='mt_version',
            field=models.CharField(default='5', help_text='MT version: 4 or 5', max_length=10),
        ),
        migrations.AlterField(
            model_name='brokerconnection',
            name='broker_type',
            field=models.CharField(choices=[('BINANCE', 'Binance'), ('BYBIT', 'Bybit'), ('KRAKEN', 'Kraken'), ('COINBASE', 'Coinbase'), ('METATRADER_CLOUD', 'MetaTrader (Cloud)'), ('METATRADER', 'MetaTrader (Local)'), ('OTHER', 'Other Exchange')], max_length=20),
        ),
    ]
