# Generated by Django 6.0.1 on 2026-01-23 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_daily_loss', models.DecimalField(decimal_places=2, help_text='Maximum allowed loss per day in USD', max_digits=10)),
                ('max_trades_per_day', models.IntegerField(default=5)),
                ('current_daily_loss', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('trades_today', models.IntegerField(default=0)),
                ('is_locked', models.BooleanField(default=False)),
                ('lock_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('last_reset_date', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
