# Generated by Django 6.0.1 on 2026-01-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskprofile',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
