# Generated by Django 6.0.1 on 2026-01-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_engine', '0002_riskprofile_locked_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskprofile',
            name='max_daily_loss',
            field=models.DecimalField(decimal_places=2, default=200.0, help_text='Maximum allowed loss per day in USD', max_digits=10),
        ),
    ]
