# Generated by Django 6.0.1 on 2026-02-02 17:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_engine', '0003_alter_riskprofile_max_daily_loss'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskprofile',
            name='last_monthly_reset',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='riskprofile',
            name='last_yearly_reset',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='riskprofile',
            name='max_trades_monthly',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='riskprofile',
            name='max_trades_yearly',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='riskprofile',
            name='trades_this_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='riskprofile',
            name='trades_this_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='riskprofile',
            name='last_reset_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
