# Generated by Django 5.2.7 on 2026-02-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_engine', '0004_riskprofile_last_monthly_reset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='riskprofile',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='If True, user cannot open new trades'),
        ),
    ]
