# Generated by Django 5.2.7 on 2026-07-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_engine', '0005_alter_riskprofile_id_alter_riskprofile_is_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskprofile',
            name='current_live_equity',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Latest equity value reported by the EA (balance + floating P&L)', max_digits=15),
        ),
        migrations.AddField(
            model_name='riskprofile',
            name='daily_start_equity',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Account equity at start of trading day. Set on first EA sync each day.', max_digits=15),
        ),
        migrations.AddField(
            model_name='riskprofile',
            name='last_ea_sync',
            field=models.DateTimeField(blank=True, help_text='Timestamp of the last successful EA heartbeat', null=True),
        ),
        migrations.AddField(
            model_name='riskprofile',
            name='max_daily_loss_pct',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Max daily drawdown as % of starting equity (e.g. 5.00 = 5%)', max_digits=5),
        ),
    ]
